### ISSUE TITLE
Can't see metrics beyond Prometheus retention time

### ISSUE THREAD

**Issue by Flybro** [improbable-eng/thanos#857]
**Thanos, Prometheus and Golang version used**
thanos, version 0.3.1-master (branch: master, revision: e1ef24d9599cdc297a2de99b4137801d0320afe9)
  build user:       thomas@bunsen
  build date:       20190220-08:53:20
  go version:       go1.11.5

prometheus, version 2.6.0 (branch: HEAD, revision: dbd1d58c894775c0788470944b818cc724f550fb)
  build user:       root@bf5760470f13
  build date:       20181217-15:14:46
  go version:       go1.11.3

**What happened**

Can't see metrics older than Prometheus retention time (72h) even if they exists in S3 (minio). Trying to access them from Prometheus cause never ending reading and no data is presented.   

**What you expected to happen**

See metrics beyond Prometheus retention time (72h)

**How to reproduce it (as minimally and precisely as possible)**:

**thanos-query:**
ExecStart=/bin/sh -c '/data01/thanos/bin/thanos-0.3.1 query \
--log.level debug \
--debug.name query-A \
--cluster.disable \
--query.replica-label promreplica \
--grpc-address 10.53.6.99:10065 \
--http-address 10.53.6.99:10070 \
--store 10.53.6.99:10050 \
--store 10.53.6.99:10080 >> /data02/thanos-log/thanos-query.log 2>&1'

**thanos-sidecar:**
ExecStart=/bin/sh -c '/data01/thanos/bin/thanos-0.3.1 sidecar \
--log.level debug \
--debug.name sidecar-A \
--cluster.disable \
--grpc-address 10.53.6.99:10050 \
--http-address 10.53.6.99:10055 \
--prometheus.url http://10.53.6.99:9901 \
--tsdb.path /data01/prometheus/data \
--objstore.config-file=/data01/thanos/conf/bucket.yml  >> /data02/thanos-log/thanos-sidecar.log 2>&1'

**thanos-store**
ExecStart=/bin/sh -c '/data01/thanos/bin/thanos-0.3.1 store \
--log.level debug \
--debug.name store-A \
--cluster.disable \
--grpc-address 10.53.6.99:10080 \
--http-address 10.53.6.99:10085 \
--data-dir /data01/thanos/cache-store \
--objstore.config-file=/data01/thanos/conf/bucket.yml  >> /data02/thanos-log/thanos-store.log 2>&1'

**bucket.yml**
---
type: S3
config:
  bucket: prometheus
  endpoint: 10.53.6.99:10999
  access-key: minio
  secret-key: **********
  insecure: false
  signature-version2: true
  encrypt-sse: false

**Full logs to relevant components**

Logs
<p>
level=debug name=query-B ts=2019-02-19T12:17:06.254940241Z caller=proxy.go:176 msg="store Addr: is-srekubemaster02p:10050 Labels: [{promreplica prom-B {} [] 0}] Mint: 1550296800000 Maxt: 9223372036854775807 queried;store Addr: is-srekubemaster01p:10050 Labels: [{promreplica prom-A {} [] 0}] Mint: 1550296800000 Maxt: 9223372036854775807 queried"
</p>

**Environment**:
- OS (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"

- Kernel (e.g. `uname -a`):
Linux 3.10.0-957.1.3.el7.x86_64

**Comment by trentza** [comment]
Confirmed i am seeing the same behaviour from GCS bucket with Thanos 0.3.1.

**Comment by bwplotka** [comment]
Thanks for report. What query you are using? You might be hitting this: https://github.com/improbable-eng/thanos/commit/0c730c1a1b52d8ded40fb58139f8282f761e20c8 that was fixed recently. Available in master and v0.3.2-rc0 docker images.

Or it might be discovery issue. What can you see on `Store` tab in Thanos UI?

**Comment by Flybro** [comment]
Hi and thank you, After compiling master branch with latest commits still having the same issue:

**thanos-query.log:**
level=warn name=query-A ts=2019-02-26T08:46:32.083885914Z caller=storeset.go:308 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.53.6.99:10080

![image](https://user-images.githubusercontent.com/10743439/53399156-ad3a9800-39ab-11e9-80ec-425d873c21eb.png)

**Comment by wklken** [comment]
> 46

I met the same warn log after upgrade to 0.3.1;

```
rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

All the stores are in the `Unknow Type` zone. 

And it works after few minutes.

**Comment by Flybro** [comment]
True that the store get alive after a few minutes but in my case getting metrics from minio newer work. All queries above 2 hours stuck for ever.

**Comment by trentza** [comment]
Hi Flybro, are you still seeing this behaviour ?

**Comment by Flybro** [comment]
Yep, still having the same issue. Thinking about reverting to 0.1.0 version :(

Cheers

**Comment by bwplotka** [comment]
Ok so this is discovery issues, right? How you guys configure querier then?

**Comment by Flybro** [comment]
You can see my whole configuration in first post but perhap you want me to make something more?

**Comment by FUSAKLA** [comment]
Hi, what's the status of this? Was the issue resolved or does it persist?

If yes could you run the query node with `--log.level=debug` if it shows some errors?
Also take a look at the `/stores` UI page of the thanos query if you see the `10.53.6.99:10080` in there and upgrade your thanos version if possible to latest. 

Please let us know if the issue persist or we can close this.
Thanks!

**Comment by Flybro** [comment]
Unfortunately,  I still can't see metrics from the S3 bucket.
**Query log:**
`level=warn name=query ts=2019-04-02T07:22:28.697913742Z caller=storeset.go:308 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.53.6.100:19691
level=warn name=query ts=2019-04-02T07:22:38.698445391Z caller=storeset.go:308 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.53.6.100:19691
level=warn name=query ts=2019-04-02T07:22:48.69916924Z caller=storeset.go:308 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.53.6.100:19691
level=warn name=query ts=2019-04-02T07:22:58.699745882Z caller=storeset.go:308 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.53.6.100:19691
level=warn name=query ts=2019-04-02T07:23:08.700283418Z caller=storeset.go:308 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=10.53.6.100:19691
level=info name=query ts=2019-04-02T07:23:18.149698687Z caller=storeset.go:250 component=storeset msg="adding new store to query storeset" address=10.53.6.100:19691`

**Store log:**
`
level=info name=store ts=2019-04-02T07:23:15.079040201Z caller=store.go:166 msg="Listening for StoreAPI gRPC" address=10.53.6.100:19691
level=info name=store ts=2019-04-02T07:23:15.079087062Z caller=main.go:308 msg="Listening for metrics" address=10.53.6.100:19791
level=debug name=store ts=2019-04-02T07:24:57.509271285Z caller=bucket.go:660 msg="Blocks source resolutions" blocks=1 mint=1554182397457 maxt=1554189897457 lset="{promreplica=\"prom-B\"}" spans="Range: 1554177600000-1554184800000 Resolution: 0"
level=debug name=store ts=2019-04-02T07:24:57.509369318Z caller=bucket.go:660 msg="Blocks source resolutions" blocks=1 mint=1554182397457 maxt=1554189897457 lset="{promreplica=\"prom-A\"}" spans="Range: 1554177600000-1554184800000 Resolution: 0"
level=debug name=store ts=2019-04-02T07:24:59.065368257Z caller=bucket.go:660 msg="Blocks source resolutions" blocks=3 mint=1554167998915 maxt=1554189898915 lset="{promreplica=\"prom-B\"}" spans="Range: 1554163200000-1554184800000 Resolution: 0"
level=debug name=store ts=2019-04-02T07:24:59.065447193Z caller=bucket.go:660 msg="Blocks source resolutions" blocks=3 mint=1554167998915 maxt=1554189898915 lset="{promreplica=\"prom-A\"}" spans="Range: 1554163200000-1554184800000 Resolution: 0"
level=debug name=store ts=2019-04-02T07:27:36.295656034Z caller=bucket.go:660 msg="Blocks source resolutions" blocks=1 mint=1554182556227 maxt=1554190056227 lset="{promreplica=\"prom-B\"}" spans="Range: 1554177600000-1554184800000 Resolution: 0"
level=debug name=store ts=2019-04-02T07:27:36.295726083Z caller=bucket.go:660 msg="Blocks source resolutions" blocks=1 mint=1554182556227 maxt=1554190056227 lset="{promreplica=\"prom-A\"}" spans="Range: 1554177600000-1554184800000 Resolution: 0"
level=debug name=store ts=2019-04-02T07:27:54.400974513Z caller=bucket.go:793 msg="series query processed" stats="&{blocksQueried:2 postingsTouched:2 postingsTouchedSizeSum:40 postingsFetched:2 postingsFetchedSizeSum:40 postingsFetchCount:2 postingsFetchDurationSum:9210358246 seriesTouched:8 seriesTouchedSizeSum:499 seriesFetched:8 seriesFetchedSizeSum:131552 seriesFetchCount:2 seriesFetchDurationSum:11957773604 chunksTouched:8 chunksTouchedSizeSum:493 chunksFetched:8 chunksFetchedSizeSum:32845 chunksFetchCount:2 chunksFetchDurationSum:12023673521 getAllDuration:18104594357 mergedSeriesCount:8 mergedChunksCount:8 mergeDuration:87321}"
level=debug name=store ts=2019-04-02T07:28:15.410526725Z caller=bucket.go:660 msg="Blocks source resolutions" blocks=3 mint=1554168195358 maxt=1554190095358 lset="{promreplica=\"prom-B\"}" spans="Range: 1554163200000-1554184800000 Resolution: 0"
level=debug name=store ts=2019-04-02T07:28:15.410609355Z caller=bucket.go:660 msg="Blocks source resolutions" blocks=3 mint=1554168195358 maxt=1554190095358 lset="{promreplica=\"prom-A\"}" spans="Range: 1554163200000-1554184800000 Resolution: 0"
level=debug name=store ts=2019-04-02T07:28:57.539434322Z caller=bucket.go:793 msg="series query processed" stats="&{blocksQueried:6 postingsTouched:6 postingsTouchedSizeSum:120 postingsFetched:4 postingsFetchedSizeSum:80 postingsFetchCount:4 postingsFetchDurationSum:45290322371 seriesTouched:24 seriesTouchedSizeSum:1496 seriesFetched:16 seriesFetchedSizeSum:263104 seriesFetchCount:4 seriesFetchDurationSum:57061097026 chunksTouched:40 chunksTouchedSizeSum:2428 chunksFetched:40 chunksFetchedSizeSum:98707 chunksFetchCount:6 chunksFetchDurationSum:66271429064 getAllDuration:42128581785 mergedSeriesCount:8 mergedChunksCount:40 mergeDuration:159135}"
`

**Comment by Flybro** [comment]
Resolved with latest 0.4.0-rc.0
